### ISSUE TITLE
subtitle files are changed to .mkv

### ISSUE THREAD

**Issue by mattmoon1123** [lemonjesus/TranscodeBot#3]
the bot passes through srt files without changing their contents, but renames them to .mkv. I assume this also happens to any other kind of file that should be passed through unchanged

**Comment by taylorz1** [comment]
should_passthrough? utilizes is_whitelisted? which correctly identifies things as .srt. The problem is this line: https://github.com/lemonjesus/TranscodeBot/blob/638c51478805c3415df55c3b7232606eb78b6464/TranscodeBot.rb#L84 where it copies it out output file which is always set to .mkv here: https://github.com/lemonjesus/TranscodeBot/blob/638c51478805c3415df55c3b7232606eb78b6464/TranscodeBot.rb#L71 probably we need a mapping function of input file format to output file format.

**Comment by lemonjesus** [comment]
fixed in version 2.1
